missions/urls.py
from django.urls import path

from missions.views import (assignment, default_assignments, mission, ship, question)

urlpatterns = [
    path('', mission.ListView.as_view(), name='mission_list'),
    path('new', mission.CreateView.as_view(), name='mission_create'),
    path('<int:pk>/', mission.DetailView.as_view(), name='mission_detail'),
    path('<int:pk>/delete', mission.DeleteView.as_view(), name='mission_delete'),
    path('<int:pk>/edit', mission.UpdateView.as_view(), name='mission_update'),
    path('ships/', ship.ListView.as_view(), name='ship_list'),
    path('ships/new', ship.CreateView.as_view(), name='ship_create'),  # TODO: Replace 'new' with 'add'
    path('ships/<int:pk>/edit/', ship.UpdateView.as_view(), name='ship_update'),
    path('ships/<int:pk>/delete/', ship.DeleteView.as_view(), name='ship_delete'),
    path('ships/<int:ship_id>/default-assignments/',
         default_assignments.ListView.as_view(),
         name='default_assignment_list'),
    path('ships/<int:ship_id>/default-assignments/add/',
         default_assignments.CreateView.as_view(),
         name='default_assignment_create'),
    path('ships/<int:ship_id>/default-assignments/<int:pk>/edit/',
         default_assignments.UpdateView.as_view(),
         name='default_assignment_update'),
    path('ships/<int:ship_id>/default-assignments/<int:pk>/delete',
         default_assignments.DeleteView.as_view(),
         name='default_assignment_delete'),
    path('<int:mission__id>/assignments/new', assignment.CreateView.as_view(), name="assignment_create"),
    path('<int:mission__id>/assignments/<int:pk>/delete',
         assignment.DeleteView.as_view(),
         name="assignment_delete"),
    path('<int:mission__id>/assignments/<int:pk>/send_mail',
         assignment.EmailView.as_view(),
         name="assignment_mail"),
    path('<int:mission__id>/assignments/<int:assignment__id>/assignee',
         assignment.UpdateView.as_view(),
         name="assignee"),
    path('questions/', question.ListView.as_view(), name='question_list'),
    path('questions/add', question.CreateView.as_view(), name='question_create'),
    path('questions/<int:pk>/delete', question.DeleteView.as_view(), name='question_delete'),
    path('questions/<int:pk>/edit', question.UpdateView.as_view(), name='question_update'),
]

seawatch_planner/urls.py
from django.contrib import admin
from django.urls import include, path

from seawatch_registration.views.index import IndexView

urlpatterns = [
    path('missions/', include('missions.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('seawatch_registration.urls')),
    path('assessments/', include('assessments.urls')),
    path('', IndexView.as_view(), name='index')
]

assessments/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from seawatch_registration.models import Profile


class Assessment(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name=_('Profile'))
    ASSESSMENT_STATUS = [
        ('pending', _('pending')),
        ('accepted', _('accepted')),
        ('rejected', _('rejected'))
    ]
    status = models.CharField(max_length=10, choices=ASSESSMENT_STATUS, verbose_name=_('Status'))
    comment = models.TextField(blank=True, verbose_name=_('Comment'))

    class Meta:
        permissions = (('can_assess_profiles', _('Set assessments for profiles')),)

missions/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils import FieldTracker

from seawatch_registration.models import Position


# Create your models here.
class Ship(models.Model):
    name = models.CharField(max_length=30, verbose_name=_('Name'))

    def __str__(self):
        return self.name


class Mission(models.Model):
    name = models.CharField(max_length=50, verbose_name=_('Name'))
    start_date = models.DateField(verbose_name=_('Start date'))
    end_date = models.DateField(verbose_name=_('End date'))
    ship = models.ForeignKey(Ship, on_delete=models.CASCADE, verbose_name=_('Ship'))

    def __str__(self):
        return self.ship.name + ": " + self.name

    def get_assigned_users(self):
        return User.objects.filter(assignments__mission=self).distinct()


class Assignment(models.Model):
    mission = models.ForeignKey(Mission, on_delete=models.CASCADE, verbose_name=_('Mission'))
    position = models.ForeignKey(Position, on_delete=models.CASCADE, verbose_name=_('Position'))
    user = models.ForeignKey(User,
                             on_delete=models.PROTECT,
                             default=None,
                             blank=True,
                             null=True,
                             related_name='assignments',)
    confirmed = models.BooleanField(default=False, verbose_name=_('Confirmed'))
    email_sent = models.BooleanField(default=False, verbose_name=_('Email sent'))

    tracker = FieldTracker(fields=['user'])


class DefaultAssignment(models.Model):
    position = models.ForeignKey(Position, on_delete=models.CASCADE, verbose_name=_('Position'))
    quantity = models.IntegerField(verbose_name=_('Quantity'))
    ship = models.ForeignKey(Ship, on_delete=models.CASCADE, related_name='default_assignments', verbose_name=_('Ship'))

    def clean(self):
        if self.quantity:
            if self.quantity < 1:
                raise ValidationError({
                    'quantity': ValidationError(_('Quantity must be at least one.'))
                })

    class Meta:
        unique_together = ('position', 'ship')

seawatch_registration/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _
from django_countries import Countries
from django_countries.fields import CountryField

from seawatch_registration.countries import data


class Nationalities(Countries):
    override = ((d['code'], _(d['demonym'] or d['name'])) for d in data)


class Skill(models.Model):
    name = models.CharField(max_length=50, verbose_name=_('Name'))
    description = models.CharField(max_length=500, blank=True, verbose_name=_('Description'))
    SKILL_GROUPS = [
        ('lang', _('language')),
        ('other', _('other'))
    ]
    group = models.CharField(max_length=10, choices=SKILL_GROUPS)

    def __str__(self):
        return self.name


class Position(models.Model):
    name = models.CharField(max_length=100, verbose_name=_('Name'))

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    citizenship = CountryField(countries=Nationalities, multiple=True, verbose_name=_('Citizenship'))
    date_of_birth = models.DateField(verbose_name=_('Date of birth'))
    place_of_birth = models.CharField(max_length=100, verbose_name=_('Place of birth'))
    country_of_birth = CountryField(verbose_name=_('Country of birth'))
    GENDER_CHOICES = [
        ('f', _('female')),
        ('m', _('male')),
        ('d', _('diverse'))
    ]
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name=_('Gender'))
    address = models.CharField(max_length=200, blank=True, verbose_name=_('Address'))
    needs_schengen_visa = models.BooleanField(verbose_name=_('Needs Schengen Visa'))
    phone = models.CharField(max_length=100, verbose_name=_('Phone'))
    emergency_contact = models.TextField(blank=True, verbose_name=_('Emergency contact'))
    comments = models.TextField(blank=True, verbose_name=_('Comments'))
    skills = models.ManyToManyField(Skill, verbose_name=_('Skills'))
    custom_skills = models.CharField(max_length=500, blank=True, verbose_name=_('Custom skills'))
    requested_positions = models.ManyToManyField(Position,
                                                 related_name='requested_profiles',
                                                 verbose_name=_('Requested Positions'))
    approved_positions = models.ManyToManyField(Position,
                                                related_name='approved_profiles',
                                                blank=True,
                                                verbose_name=_('Approved Positions'))

    def __str__(self):
        return self.user.last_name + ", " + self.user.first_name

    def get_joined_citizenship_list(self, delimiter=', '):
        return delimiter.join(c.name for c in self.citizenship)


class DocumentType(models.Model):
    name = models.CharField(max_length=100, verbose_name=_('Name'))
    DOCUMENT_TYPE_GROUPS = [
        ('ident', _('identification documents and visa')),
        ('nautic', _('nautical qualification')),
        ('engineer', _('engineer qualification')),
        ('seafarer', _('seafarer qualification')),
        ('other', _('other qualification'))
    ]
    group = models.CharField(max_length=10, choices=DOCUMENT_TYPE_GROUPS, verbose_name=_('Category'))

    def __str__(self):
        return self.name


class Document(models.Model):
    document_type = models.ForeignKey(DocumentType, on_delete=models.CASCADE, verbose_name=_('Document type'))
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name=_('Profile'))
    number = models.CharField(max_length=100, blank=True, verbose_name=_('Number'))
    issuing_date = models.DateField(null=True, blank=True, verbose_name=_('Issuing date'))
    expiry_date = models.DateField(null=True, blank=True, verbose_name=_('Expiry date'))
    issuing_authority = models.CharField(max_length=100, blank=True, verbose_name=_('Issuing authority'))
    issuing_place = models.CharField(max_length=100, blank=True, verbose_name=_('Issuing place'))
    issuing_country = models.CharField(max_length=100, blank=True, verbose_name=_('Issuing country'))
    file = models.FileField(verbose_name=_('File'))

    def __str__(self):
        return f'{self.number} ({self.document_type})'


class Question(models.Model):
    text = models.CharField(max_length=500, verbose_name=_('Text'))
    mandatory = models.BooleanField(verbose_name=_('Madatory'))
    profiles = models.ManyToManyField(Profile, through='Answer', verbose_name=_('Profiles'))

    def __str__(self):
        return self.text


class Answer(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name=_('Profile'))
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name=_('Question'))
    text = models.TextField(verbose_name=_('Text'))

    def __str__(self):
        return self.text


class Availability(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name=_('Profile'))
    start_date = models.DateField(verbose_name=_('Start date'))
    end_date = models.DateField(verbose_name=_('End date'))
    comment = models.CharField(max_length=255, blank=True, verbose_name=_('Comment'))

    def __str__(self):
        return f'{self.start_date.strftime("%x")} – {self.end_date.strftime("%x")} ({self.profile})'

    def clean(self):
        if self.start_date and self.end_date:
            if self.start_date > self.end_date:
                raise ValidationError({
                    'start_date': ValidationError(_('Cannot select an empty date range.')),
                    'end_date': ValidationError(_('Cannot select an empty date range.')),
                })

missions/views/default_assigments.py
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic

from missions.models import DefaultAssignment, Ship


class CreateView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    model = DefaultAssignment
    fields = ['position', 'quantity']
    nav_item = 'ships'
    permission_required = 'missions.add_defaultassignment'

    def get_success_url(self):
        ship_id = self.kwargs.get('ship_id')
        return reverse('default_assignment_list', kwargs={'ship_id': ship_id})

    def form_valid(self, form):
        ship_id = self.kwargs.get('ship_id')
        if DefaultAssignment.objects.filter(position=form.cleaned_data['position'], ship=ship_id).exists():
            form.add_error('position', 'There is already a default assignment for this position for this ship!')
            return self.form_invalid(form)

        form.instance.ship = get_object_or_404(Ship, pk=ship_id)
        return super(CreateView, self).form_valid(form)


class UpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    model = DefaultAssignment
    fields = ['position', 'quantity']
    nav_item = 'ships'
    permission_required = 'missions.add_defaultassignment'

    def get_success_url(self):
        ship_id = self.kwargs.get('ship_id')
        return reverse('default_assignment_list', kwargs={'ship_id': ship_id})

    def form_valid(self, form):
        ship_id = self.kwargs.get('ship_id')
        form.instance.ship = get_object_or_404(Ship, pk=ship_id)
        return super(UpdateView, self).form_valid(form)


class ListView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    model = DefaultAssignment
    paginate_by = 10
    nav_item = 'ships'
    ordering = 'id'
    permission_required = 'missions.view_defaultassignment'

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        ship_id = self.kwargs.get('ship_id')
        context['ship'] = get_object_or_404(Ship, pk=ship_id)
        return context

    def get_queryset(self):
        ship_id = self.kwargs.get('ship_id')
        return DefaultAssignment.objects.filter(ship__id=ship_id)


class DeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    model = DefaultAssignment
    nav_item = 'ships'
    permission_required = 'missions.delete_defaultassignment'

    def get_success_url(self):
        ship_id = self.kwargs.get('ship_id')
        return reverse('default_assignment_list', kwargs={'ship_id': ship_id})

    def get_context_data(self, **kwargs):
        context = super(DeleteView, self).get_context_data(**kwargs)
        ship_id = self.kwargs.pop('ship_id')
        context['ship'] = get_object_or_404(Ship, pk=ship_id)
        return context

missions/views/default_assignments.py
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views import generic

from missions.models import DefaultAssignment, Ship


class DefaultAssignmentForm(ModelForm):

    def clean_position(self):
        position = self.cleaned_data['position']
        if self.instance.pk is None and DefaultAssignment.objects.filter(
                position=position, ship=self.initial.get('ship_id')).exists():
            raise ValidationError(_('There is already a default assignment for this position for this ship.'))
        return position

    def clean(self):
        self.instance.ship = Ship.objects.get(pk=self.initial.get('ship_id'))
        return super().clean()

    class Meta:
        model = DefaultAssignment
        fields = ('position', 'quantity')


class DefaultAssignmentBaseView(LoginRequiredMixin, PermissionRequiredMixin, generic.View):
    nav_item = 'ships'
    model = DefaultAssignment
    form_class = DefaultAssignmentForm
    permission_required = 'missions.add_defaultassignment'

    def get_success_url(self):
        ship_id = self.kwargs.get('ship_id')
        return reverse('default_assignment_list', kwargs={'ship_id': ship_id})

    def get_initial(self):
        return {'ship_id': self.kwargs.get('ship_id')}

    def get_context_data(self, **kwargs):
        return {**super().get_context_data(**kwargs),
                'ship': get_object_or_404(Ship, pk=(self.kwargs.get('ship_id')))}


class ListView(DefaultAssignmentBaseView, generic.ListView):
    paginate_by = 10
    ordering = 'id'

    def get_queryset(self):
        ship_id = self.kwargs.get('ship_id')
        return DefaultAssignment.objects.filter(ship__id=ship_id)


class CreateView(DefaultAssignmentBaseView, generic.CreateView):
    pass


class UpdateView(DefaultAssignmentBaseView, generic.UpdateView):
    pass


class DeleteView(DefaultAssignmentBaseView, generic.DeleteView):
    pass

missions/templates/missions/assignee_form.html
{% extends "base-missions.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block content %}
    <article>
        <h1>{% trans "Assign volunteers" %}</h1>
        <section>
            <ul>
                <li>
                    {% trans "Mission" %}: <strong>{{ mission.name }}</strong>
                </li>
                <li>
                    {% trans "Ship" %}: <strong>{{ mission.ship.name }}</strong>
                </li>
                <li>
                    {% trans "Time period" %}: <strong>{{ mission.start_date }} - {{ mission.end_date }}</strong>
                </li>
                <li>
                    {% trans "Selected position" %} <strong>{{ object.position.name }}</strong>
                </li>
            </ul>
        </section>

        <section>
            <button id="collapse-button" class="btn btn-link" type="button" data-toggle="collapse"
                    data-target="#filter-collapse"
                    aria-expanded="{{ request.GET.show_filter|default:'false' }}" aria-controls="filter-collapse">
                {% trans "Show filter" %}
            </button>
            <div class="collapse {% if request.GET.show_filter == 'true' %}show{% endif %} card card-body"
                 id="filter-collapse">
                <form method="get" class="form">
                    {% bootstrap_form filter_form %}
                    {# The filter should not disappear after hitting the filter button #}
                    <input type="hidden" name="show_filter" value="true">
                    {% buttons submit='Filter' %}
                        <a id="reset-button" class="btn btn-outline-danger" href="{{ reset_url }}&show_filter=true">
                            {% trans 'Reset to mission parameters' %}
                        </a>
                    {% endbuttons %}
                </form>
            </div>
            <script>
                document.getElementById('collapse-button').addEventListener('click', _ => {
                    const params = new URLSearchParams(location.search);
                    params.set('show_filter', params.get('show_filter') === 'true' ? 'false' : 'true');
                    window.history.replaceState({}, '', `${location.pathname}?${params}`);
                });
            </script>
        </section>

        <section>
            <form method="post">
                {% csrf_token %}
                {% include "partials/form-errors.html" %}
                <table class="table">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col"></th>
                        <th scope="col">{% trans 'Assignee' %}</th>
                        <th scope="col">{% trans 'Requested positions' %}</th>
                        <th scope="col">{% trans 'Approved positions' %}</th>
                        <th scope="col">{% trans 'Availability' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for profile in profiles %}
                        <tr class="assignee-row" data-assignee-id="{{ profile.pk }}">
                            <td><input id="assignee_{{ profile.pk }}" type="radio" name="assignee"
                                       value="{{ profile.pk }}"
                                       {% if profile.user.pk == assignment.user.pk %}checked{% endif %}></td>
                            <td>
                                {% with name=profile.user.first_name|add:" "|add:profile.user.last_name %}
                                    {% if profile.assessment_set.exists %}
                                        <a class="assessment-link"
                                           href="{% url 'assessment_update' pk=profile.assessment_set.first.pk %}">
                                            {{ name }}
                                        </a>
                                    {% else %}
                                        <label for="assignee_{{ profile.pk }}">{{ name }}</label>
                                    {% endif %}
                                {% endwith %}
                            </td>
                            <td>{{ profile.requested_positions.all|join:", " }}</td>
                            <td>{{ profile.approved_positions.all|join:", " }}</td>
                            <td>
                                {% for availability in profile.availability_set.all %}
                                    {{ availability.start_date }} - {{ availability.end_date }}
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <button id="save-button" type="submit" class="btn btn-primary" name="Save" value="save">Save</button>
                <button id="return-button" type="submit" class="btn btn-primary-outline" name="return_to_mission"
                        value="true">
                    Cancel and back to mission
                </button>
            </form>
            <script>
                for (let row of document.getElementsByClassName('assignee-row')) {
                    let inputId = 'assignee_' + row.dataset.assigneeId;
                    row.addEventListener('click', _ => {
                        document.getElementById(inputId).checked = true;
                    });
                }

                for (let link of document.getElementsByClassName('assessment-link')) {
                    link.addEventListener('click', event => event.stopPropagation());
                }
            </script>
        </section>
    </article>
{% endblock %}

missions/templates/missions/assignment_confirm_delete.html
{% extends 'base-registration.html' %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}Missions | Seawatch Missions{% endblock %}

{% block content %}
    <h1>
        {% blocktrans trimmed with position_name=object.position.name mission_name=object.mission.name %}
        Delete assignment "{{ position_name }}" for mission "{{ mission_name }}"
        {% endblocktrans %}
    </h1>

    <form method="post">{% csrf_token %}
        <p>
            {% blocktrans trimmed with position_name=object.position.name mission_name=object.mission.name%}
            Are you sure you want to delete assignment "{{ position_name }}" for mission "{{ mission_name }}"?
            {% endblocktrans %}
        </p>
        <input class="btn btn-primary" type="submit" value="{% trans 'Confirm' %}">
        <a class="btn btn-primary"href="{% url 'mission_detail' object.mission.id %}" role="button">{% trans "Cancel" %}</a>
    </form>
{% endblock %}

missions/templates/missions/assignment_form.html
{% extends "base-missions.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block content %}

    <h1>{% trans "Create new position" %}</h1>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-primary" type="submit" value="{% trans 'Save' %}">
    </form>

{% endblock %}

missions/templates/missions/defaultassignment_detail.html
{% extends 'base-registration.html' %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}Mission | Seawatch Missions{% endblock %}

{% block content %}
<h1>{% blocktrans with name=obejct.name %}Ship {{ name }}{% endblocktrans %}</h1>
<p><strong>{% trans 'Name:' %} </strong>{{ object.name }}</p>
{% endblock %}

missions/templates/missions/defaultassignment_form.html
{% extends 'base-registration.html' %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}Default Assignment | Seawatch Missions{% endblock %}

{% block content %}
<h1>{% trans 'Default Assignment' %}</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}

    <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
</form>
{% endblock %}

missions/templates/missions/mission_assignment_editor.html
{% extends 'base-registration.html' %}
{% load bootstrap4 %}

{% block title %}Missions | Seawatch Missions{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <section class="row">

            <div class="col-6">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Position</th>
                        <th scope="col">Taken by</th>
                        <th scope="col">Other</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for assignment in mission.assignment_set.all|dictsort:"position.name" %}
                        <tr>
                            <td>{{ assignment.position }}</td>
                            <td>{{ assignment.user.email }}</td>
                            <td>
                                <button id="assignment_pk" class="btn btn-primary" type="submit" name="assignment_pk"
                                        value="{{ assignment.pk }}">
                                    Assign
                                </button>
                                <label for="assignment_pk"></label>
                            </td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="3"><a href="{% url 'assignment_create' mission.pk %}">Add assignment</a></td>
                    </tr>
                    </tbody>
                </table>
            </div>

            <div class="col-6">
                {% for candidate in candidates %}
                    <div class="form-check">
                        <label class="form-check-label">
                            <input class="form-check-input"
                                   type="radio"
                                   name="assignee_pk"
                                   value="{{ candidate.pk }}"
                            />
                            {{ candidate.user.email }}
                        </label>
                    </div>
                {% endfor %}
            </div>

        </section>
    </form>
{% endblock %}

missions/templates/missions/mission_detail.html
{% extends "base-missions.html" %}
{% load bootstrap4 %}
{% load fontawesome_5 %}
{% load i18n %}


{% block content %}
    <script type="text/javascript">
        function AlertMultipleAssignmentsInSameMission(first_name, last_name) {
            alert(first_name + " " + last_name + " is assigned multiple times for this mission")
        }

        function AlertMultipleAssignmentsInDifferentMission(first_name, last_name) {
            alert(first_name + " " + last_name + " is assigned to a different mission in the same timeperiod")
        }
    </script>

    <h1>{% blocktrans with ship_name=object.ship.name mission_name=object.name %}{{ ship_name }}: Mission ”
        {{ mission_name }}”{% endblocktrans %}</h1>
    <p>{% blocktrans with start_date=object.start_date end_date=object.end_date %}From {{ start_date }} to
        {{ end_date }}{% endblocktrans %}</p>
    <h2>{% trans 'Assignments' %}</h2>
    <table class="table">
        <thead>
        <tr>
            {% if multiple_assigned_users or multiple_assigned_users_in_different_missions %}
                <th scope="col"></th>
            {% endif %}
            <th scope="col">{% trans 'Position' %}</th>
            <th scope="col">{% trans 'Assignment' %}</th>
            <th scope="col">{% trans 'Confirmation' %}</th>
            <th scope="col">{% trans 'Actions' %}</th>
        </tr>
        </thead>
        <tbody>
        {% for assignment in object.assignment_set.all %}
            <tr>
                {% if multiple_assigned_users or multiple_assigned_users_in_different_missions %}

                    <td>
                        {% if assignment.user in multiple_assigned_users %}
                            <a class="text-danger"
                               href="javascript:AlertMultipleAssignmentsInSameMission('{{ assignment.user.first_name }}','{{ assignment.user.last_name }}');">
                                {% fa5_icon 'exclamation-triangle' 'fas' %}
                            </a>
                        {% endif %}
                        {% if assignment.user in multiple_assigned_users_in_different_missions %}
                            <a class="text-danger"
                               href="javascript:AlertMultipleAssignmentsInDifferentMission('{{ assignment.user.first_name }}','{{ assignment.user.last_name }}');">
                                {% fa5_icon 'exclamation-triangle' 'fas' %}
                            </a>
                        {% endif %}
                    </td>
                {% endif %}
                <td>{{ assignment.position.name }}</td>
                <td>{{ assignment.user.first_name }} {{ assignment.user.last_name }}</td>
                <td>{{ assignment.confirmed }}</td>
                <td>
                    {% with date_format="Y-m-d" %}
                        <a id="assignee" href="{% url 'assignee' object.id assignment.id %}?position={{ assignment.position.name|urlencode }}&start_date={{ mission.start_date|date:date_format }}&end_date={{ mission.end_date|date:date_format }}"
                           data-toggle="tooltip"
                           title="{% comment %}Translators: Text for Tooltip{% endcomment %}{% trans 'assign volunteer' %}">
                            {% fa5_icon 'user' 'fas' %}
                        </a>
                    {% endwith %}
                    {% if not assignment.email_sent and assignment.user %}
                        <a id="assignment_mail" href="{% url 'assignment_mail' object.id assignment.id %}" data-toggle="tooltip"
                           title="{% comment %}Translators: Text for Tooltip{% endcomment %}{% trans 'send mission information email' %}">
                            {% fa5_icon 'envelope' 'fas' %}
                        </a>
                    {% else %}
                        <a class="text-black-50" data-toggle="tooltip"
                           title="{% comment %}Translators: Text for Tooltip{% endcomment %}{% trans 'send mission information email' %}">
                            {% fa5_icon 'envelope' 'fas' %}
                        </a>
                    {% endif %}
                    <a id="assignment_delete" class="text-danger" href="{% url 'assignment_delete' object.id assignment.id %}"
                       data-toggle="tooltip"
                       title="{% comment %}Translators: Text for Tooltip{% endcomment %}{% trans 'delete' %}">
                        {% fa5_icon 'trash' 'fas' %}
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{% url 'assignment_create' object.id %}"
       role="button">{% fa5_icon 'plus' 'fas' %}</a>
{% endblock %}